apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-armor
spec:
  type: NodePort
  ports:
    - name: traefik
      port: 80
      nodePort: 30182
      targetPort: 80
  selector:
    app.kubernetes.io/instance: traefik-traefik-armor