apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: env-intern
spec:
  selector:
    app: devsecops
  ports:
    - port: 3000
      targetPort: 8080
    - port: 8080
      targetPort: 8080