apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: env-intern
spec:
  selector:
    app: devsecops
  ports:
    - name: http-frontend
      port: 80
      targetPort: 3000
    - name: http-backend
      port: 8080
      targetPort: 8080