apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc
  labels:
    vol: prom-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
