name: Container images scanning
on: push
jobs:
  container-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Trivy vulnerability scanner for frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'europe-west1-docker.pkg.dev/z-devsecops-cloud/z-devsecops-registry/frontend:latest'
          format: 'sarif'
          output: 'trivy-results-frontend.sarif'

      - name: Run Trivy vulnerability scanner for backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'europe-west1-docker.pkg.dev/z-devsecops-cloud/z-devsecops-registry/backend:latest'
          format: 'sarif'
          output: 'trivy-results-backend.sarif'

      - name: Upload Trivy scan results to GitHub Security tab (frontend)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-frontend.sarif'

      - name: Upload Trivy scan results to GitHub Security tab (backend)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-backend.sarif'