name: Create PR

on:
  push:
    branches: [ "eph" ]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: create pull request
        run: gh pr create -B main -H eph --title 'Merge eph into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}