name: Security workflow

on:
  pull_request:
    types: [ closed ]

jobs:
  DAST:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write
      issues: write

    steps:
      ## DAST
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://front.34.111.30.200.nip.io'
          cmd_options: "-d" #show debug messages
          docker_name: 'owasp/zap2docker-stable'