name: Main CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  My_CI_job:
  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        java: ['17', '18', '19']
    env: 
      frontend_working_directory: ./frontend
      backend_working_directory: ./backend
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B --update-snapshots package --file ${{env.backend_working_directory}}/pom.xml
    - name: Setup staging environment
      run: mkdir staging && cp ${{env.backend_working_directory}}/target/*.jar staging
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-${{ matrix.java }}.JAR
        path: staging
       
    - uses: actions/checkout@v3
    - name: Build the Docker image for VueJS frontend
      run: docker build ${{env.frontend_working_directory}} --file ${{env.frontend_working_directory}}/Dockerfile -t my-frontend-image:$(date +%s)
    - name: Build the Docker image for Spring Boot backend
      run: docker build ${{env.backend_working_directory}} --file ${{env.backend_working_directory}}/Dockerfile --build-arg JAR_FILE="staging/${{ matrix.os }}-${{ matrix.java }}.JAR" -t my-backend-image:$(date +%s)
