name: Main CI

on:
  push:
    branches: [ "main" ]
    
env:
  FRONTEND: ./frontend
  BACKEND: ./backend
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
    
jobs:
  build-and-upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B --update-snapshots package --file ${{env.BACKEND}}/pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Package
        path: ${{env.BACKEND}}/target

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker Frontend image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{env.FRONTEND}}
          file: ${{env.FRONTEND}}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/frontend:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker Backend image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{env.BACKEND}}
          file: ${{env.BACKEND}}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
          labels: ${{ steps.meta.outputs.labels }}