name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B --update-snapshots package  --file ${{env.working-directory}}/pom.xml
    - name: Setup staging environment
      run: mkdir staging && cp target/*.jar staging
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
