name: Merge PR

on:
  pull_request:
    types: [closed]

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write
      issues: write
      statuses: write

    steps:
      - uses: actions/checkout@v3

      - name: Deploy docker images to the GKE cluster in prod
        env:
          MANIFESTS: deployment
          DEPLOYMENTS: deployment/dp
          NAMESPACES: deployment/namespaces
          SERVICES: deployment/services
        run: |-
          kubectl apply -f ${{ github.workspace }}/$NAMESPACES/prod.yml
          kubectl apply -f ${{ github.workspace }}/$DEPLOYMENTS/frontend.yml -n prod
          kubectl apply -f ${{ github.workspace }}/$DEPLOYMENTS/backend.yml -n prod
          kubectl apply -f ${{ github.workspace }}/$SERVICES/api.yml -n prod
          kubectl apply -f ${{ github.workspace }}/$SERVICES/frontend.yml -n prod

      ## DAST
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://front.34.111.30.200.nip.io'
          cmd_options: "-d" #show debug messages
          docker_name: 'owasp/zap2docker-stable'

      - name: Delete eph branch
        run: |-
          git branch -d eph
          git push origin --delete eph