name: SAST scanning
on: push
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # SAST scanning
      - name: Create .mvn directory
        run: |-
          cd ${{ github.workspace }}/backend &&
          mvn -N io.takari:maven:wrapper

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects
          json: true