name: Terraform plan
on:
  pull_request:
    types: [ opened, synchronize ]

env:
  GKE_CLUSTER: tf-gke-cluster
  GKE_ZONE: europe-west9-a
  SA: github-action-sa@z-devsecops-cloud.iam.gserviceaccount.com
  WORKLOAD_ID_PROVIDER: projects/599822394994/locations/global/workloadIdentityPools/cicd/providers/github

jobs:
  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write
      issues: write
      statuses: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        id: auth
        with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ env.WORKLOAD_ID_PROVIDER }}
          service_account: ${{ env.SA }}

      - name: Configure Docker to use the gcloud command-line tool as a credential
        run: |
          gcloud config set disable_prompts true
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud --quiet auth configure-docker europe-west1-docker.pkg.dev

      - name: Get the GKE credentials
        uses: google-github-actions/get-gke-credentials@v1.0.1
        with:
          project_id: z-devsecops-cloud
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      #- run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

      - uses: hashicorp/setup-terraform@v2

      - name: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: init
        run: terraform init

      - name: validate
        id: validate
        run: terraform validate -no-color

      - name: plan
        run: terraform plan -no-color
        continue-on-error: true